[package]
name = "tokterm_termion"
version = "0.1.0"
authors = ["Pablo Ordoñez <pabloo84@gmail.com>"]

[dependencies.tokterm_core]
path = "../tokterm_core"
version = "0.1.0"

[dependencies.termion]
version = "*"